drush/drush:
  core_matrix:
    9.x:
      version: 11.x
      version_dev: 11.x
    '*':
      version: 12.x
      version_dev: 12.x-dev

weitzman/drupal-test-traits:
  version: '*'
  version_dev: '*'