name: Create JIRA Issue from Dependabot PR

on:
  push:
    branches:
      - test1

jobs:
  create_jira_issue:
#    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.jira-user-email }}
          JIRA_API_TOKEN: ${{ secrets.jira-api-token }}

