---
name: ORCA Action
on:
    push:
        branches: [ main, develop, wip, support/** ]
        paths-ignore:
            - .idea/**
            - docs/**
    pull_request:
        branches: [ develop ]
        paths-ignore:
            - .idea/**
            - docs/**
    schedule:
        # Daily at 00:00:00 UTC.
        # @see https://crontab.cronhub.io/
        -   cron: "0 0 * * *"
jobs:
  action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        orca-job:
          - STATIC_CODE_ANALYSIS
          - INTEGRATED_TEST_ON_OLDEST_SUPPORTED
          - INTEGRATED_TEST_ON_LATEST_LTS
          - INTEGRATED_TEST_ON_PREVIOUS_MINOR
          - INTEGRATED_UPGRADE_TEST_FROM_PREVIOUS_MINOR
          - ISOLATED_TEST_ON_CURRENT
          - INTEGRATED_TEST_ON_CURRENT
          - INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR
          - ISOLATED_TEST_ON_CURRENT_DEV
          - INTEGRATED_TEST_ON_CURRENT_DEV
          - STRICT_DEPRECATED_CODE_SCAN
          - ISOLATED_TEST_ON_NEXT_MINOR
          - INTEGRATED_TEST_ON_NEXT_MINOR
          - ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_BETA_OR_LATER
          - ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_DEV
          - DEPRECATED_CODE_SCAN_W_CONTRIB
          - INTEGRATED_TEST_ON_NEXT_MINOR_DEV
          - ISOLATED_TEST_ON_NEXT_MINOR_DEV
          - INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR_DEV
          - LOOSE_DEPRECATED_CODE_SCAN
          # - ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER
          # - INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER
          # - ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
          # - INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV
        php-version: [ "7.4" ]
        include:
          - orca-job: ISOLATED_TEST_ON_CURRENT
            php-version: "8.0"

          # @TODO uncomment. is ORCA_JOB not required?
          # - orca-job: ""
          #   orca-live-test: "TRUE"
          #   php-version: "7.4"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: ORCA
        uses: ./
        with:
          sut_name: drupal/example
          sut_branch: main
          packages_config: example/tests/packages.yml
          packages_config_alter: example/tests/packages_alter.yml
          enable_nightwatch: "FALSE"
          # Hardcode path since GITHUB_WORKSPACE can't be used here.
          # @see https://github.community/t/how-to-use-env-context/16975/9
          sut_dir: /home/runner/work/orca/example
          self_test_coverage_clover: $HOME/build/logs/clover-self.xml
          job: ${{ matrix.orca-job }}
          live_test: ${{ matrix.orca-live-test }}
