name: Update Packages and Create Pull Request

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Mondays
  push:
    branches:
      - wip # Trigger on pushes to wip branch
    paths-ignore:
      - .idea/**
      - docs/**

permissions:
  contents: write
  pull-requests: write

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      # Step 3: Add/Update Dependencies
      - name: Add Guzzle Dependency
        run: composer require guzzlehttp/guzzle:^7.4

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: composer install

      # Step 5: Run Update Script
      - name: Run Update Script
        run: php .github/update_packages.php

      # Step 6: Reset or Recreate Branch
      - name: Reset or Recreate Branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout wip
          git branch -D update-packages || true
          git checkout -b update-packages
          git add config/packages.yml
          if git diff --staged --quiet; then
            echo "No changes detected; adding dummy commit."
            echo "# Dummy commit to trigger PR" >> config/packages.yml
            git add config/packages.yml
            git commit -m "Dummy commit to trigger PR"
          else
            git commit -m "Update dependencies in packages.yml"
          fi
          git push origin update-packages --force

      # Step 7: Create or Update Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-packages
          base: wip
          title: Update packages.yml with latest versions
          body: |
            This pull request updates the `packages.yml` file with the latest stable versions of dependencies.
            If no changes are detected, this is a placeholder PR for consistency.
          labels: dependencies
          delete-branch: true
